# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 18:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Corso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('autori', models.CharField(max_length=100)),
                ('ripetuto', models.BooleanField(default=False)),
                ('lunedi1', models.BooleanField(default=False)),
                ('lunedi2', models.BooleanField(default=False)),
                ('lunedi3', models.BooleanField(default=False)),
                ('martedi1', models.BooleanField(default=False)),
                ('martedi2', models.BooleanField(default=False)),
                ('martedi3', models.BooleanField(default=False)),
                ('mercoledi1', models.BooleanField(default=False)),
                ('mercoledi2', models.BooleanField(default=False)),
                ('mercoledi3', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
