# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171030_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='iscrizione',
            name='fascia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.Fascia'),
        ),
    ]
