# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_iscrizione_fascia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iscrizione',
            name='fascia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Fascia'),
        ),
    ]
