# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20171030_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corso',
            old_name='nome',
            new_name='titolo',
        ),
        migrations.AddField(
            model_name='corso',
            name='classi',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='corso',
            name='descrizione',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='iscrizione',
            name='lunedi1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='iscrizione',
            name='lunedi2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='iscrizione',
            name='lunedi3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='iscrizione',
            name='martedi1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='iscrizione',
            name='martedi2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='iscrizione',
            name='martedi3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='iscrizione',
            name='mercoledi1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='iscrizione',
            name='mercoledi2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='iscrizione',
            name='mercoledi3',
            field=models.BooleanField(default=False),
        ),
    ]
