# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_aula'),
    ]

    operations = [
        migrations.AddField(
            model_name='corso',
            name='aule',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.Aula'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='aule',
            field=models.CharField(default='', max_length=100),
        ),
    ]
