# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 18:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20171031_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corso',
            name='aule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Aula'),
        ),
    ]
