# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 10:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_iscrizione_corso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iscrizione',
            name='fascia',
        ),
    ]
