# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_iscrizione_fascia'),
    ]

    operations = [
        migrations.AddField(
            model_name='iscrizione',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='iscrizione',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
