# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20171101_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iscrizione',
            name='fascie',
        ),
        migrations.AddField(
            model_name='iscrizione',
            name='lunedi1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='iscrizione',
            name='lunedi2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='iscrizione',
            name='lunedi3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='iscrizione',
            name='martedi1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='iscrizione',
            name='martedi2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='iscrizione',
            name='martedi3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='iscrizione',
            name='mercoledi1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='iscrizione',
            name='mercoledi2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='iscrizione',
            name='mercoledi3',
            field=models.BooleanField(default=False),
        ),
    ]
