# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 15:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0014_auto_20171101_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iscrizione',
            name='author',
        ),
        migrations.AddField(
            model_name='iscrizione',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
