# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20171101_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fascia',
            name='corso',
        ),
        migrations.AddField(
            model_name='corso',
            name='lunedi1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='corso',
            name='lunedi2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='corso',
            name='lunedi3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='corso',
            name='martedi1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='corso',
            name='martedi2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='corso',
            name='martedi3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='corso',
            name='mercoledi1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='corso',
            name='mercoledi2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='corso',
            name='mercoledi3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='corso',
            name='ripetuto',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Fascia',
        ),
    ]
