# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 17:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20171101_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iscrizione',
            name='corso',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Corso'),
        ),
        migrations.AlterField(
            model_name='iscrizione',
            name='user',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
