# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20171102_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iscrizione',
            name='corso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Corso'),
        ),
    ]
