# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20171102_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='iscrizione',
            name='aule',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.Aula'),
        ),
    ]
