# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 07:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20171104_0740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iscrizione',
            name='lunedi1',
        ),
        migrations.RemoveField(
            model_name='iscrizione',
            name='lunedi2',
        ),
        migrations.RemoveField(
            model_name='iscrizione',
            name='lunedi3',
        ),
        migrations.RemoveField(
            model_name='iscrizione',
            name='martedi1',
        ),
        migrations.RemoveField(
            model_name='iscrizione',
            name='martedi2',
        ),
        migrations.RemoveField(
            model_name='iscrizione',
            name='martedi3',
        ),
        migrations.RemoveField(
            model_name='iscrizione',
            name='mercoledi1',
        ),
        migrations.RemoveField(
            model_name='iscrizione',
            name='mercoledi2',
        ),
        migrations.RemoveField(
            model_name='iscrizione',
            name='mercoledi3',
        ),
    ]
