# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 11:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20171104_0743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corso',
            old_name='classi',
            new_name='classi_autori',
        ),
        migrations.RemoveField(
            model_name='iscrizione',
            name='aule',
        ),
    ]
