# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20171104_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iscrizione',
            old_name='corso',
            new_name='corso1',
        ),
        migrations.AddField(
            model_name='iscrizione',
            name='corso2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='app.Corso'),
        ),
    ]
