# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20171104_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='iscrizione',
            name='corso3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corso3', to='app.Corso'),
        ),
        migrations.AddField(
            model_name='iscrizione',
            name='corso4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corso4', to='app.Corso'),
        ),
        migrations.AddField(
            model_name='iscrizione',
            name='corso5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corso5', to='app.Corso'),
        ),
        migrations.AddField(
            model_name='iscrizione',
            name='corso6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corso6', to='app.Corso'),
        ),
        migrations.AddField(
            model_name='iscrizione',
            name='corso7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corso7', to='app.Corso'),
        ),
        migrations.AddField(
            model_name='iscrizione',
            name='corso8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corso8', to='app.Corso'),
        ),
        migrations.AddField(
            model_name='iscrizione',
            name='corso9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corso9', to='app.Corso'),
        ),
        migrations.AlterField(
            model_name='iscrizione',
            name='corso1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corso1', to='app.Corso'),
        ),
        migrations.AlterField(
            model_name='iscrizione',
            name='corso2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corso2', to='app.Corso'),
        ),
    ]
