# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-04 18:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20171104_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corso',
            old_name='autori',
            new_name='studenti_referenti',
        ),
    ]
