# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20171104_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corso',
            old_name='lunedi1',
            new_name='f1',
        ),
        migrations.RenameField(
            model_name='corso',
            old_name='lunedi2',
            new_name='f2',
        ),
        migrations.RenameField(
            model_name='corso',
            old_name='lunedi3',
            new_name='f3',
        ),
        migrations.RenameField(
            model_name='corso',
            old_name='martedi1',
            new_name='f4',
        ),
        migrations.RenameField(
            model_name='corso',
            old_name='martedi2',
            new_name='f5',
        ),
        migrations.RenameField(
            model_name='corso',
            old_name='martedi3',
            new_name='f6',
        ),
        migrations.RenameField(
            model_name='corso',
            old_name='mercoledi1',
            new_name='f7',
        ),
        migrations.RenameField(
            model_name='corso',
            old_name='mercoledi2',
            new_name='f8',
        ),
        migrations.RenameField(
            model_name='corso',
            old_name='mercoledi3',
            new_name='f9',
        ),
    ]
