# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20171112_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iscrizione',
            name='corso1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corso1', to='app.Corso'),
        ),
    ]
